### ISSUE TITLE
Hello! Do you have any plans of ending support for Cassandra 3.x

### ISSUE THREAD

**Issue by CarlosGCA** [k8ssandra/k8ssandra-operator#1436]
Hello! We are currently using `k8ssandra-operator` to deploy Cassandra 3.11.12 (serverVersion: 3.11.12) in AWS EKS.

Our Cassandra Servers are working fine so far. However, with the release of Cassandra 5 we are worried about our deployment process for Cassandra becoming obsolete. As far as I know, `k8ssandra-operator` allows users to deploy Cassandra versions 3.x and 4.x. So my questions is: **Do you have any plans of ending support for Cassandra 3.x in the short of long term? Should we start thinking in upgrading our current Cassandra deployments from 3.11.12 to 4.x ?**

Kind regards,
Carlos Carrillo
Cloud Engineer

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-280) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-280

**Comment by burmanm** [comment]
Hi, we will most likely drop building new images for 3.11 quite soon as per this ticket: https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/547

What this means in reality is that new features will no longer be supported for 3.11 and any possible bugs that would require fix in the management-api are not going to be fixed. Also, we will no longer test 3.11 deployments in our operators (cass-operator has already removed these tests in https://github.com/k8ssandra/cass-operator/pull/712 so k8ssandra-operator is impacted). 

I would really recommend updating Cassandra, since the upstream won't provide fixes to it either (even CVEs). That doesn't mean your cluster is going to stop it working overnight and we will not actively remove the ability to deploy 3.11 at this point. But it might be wise to stick to a version that still supported 3.11, so 1.20.2 and older (for k8ssandra-operator).

**Comment by burmanm** [comment]
I'll close this as we've stopped producing new 3.11 images and removed most of the testing. Future versions might break compatibility with 3.11.
