### ISSUE TITLE
Investigate running e2e tests on self-hosted GH runners

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#165]
**What is missing?**

A capability to run more resource intensive integration tests on hardware with great capabilities than the free-tier GH runners.

**Why do we need it?**

We have continuously faced stability issues with our larger multi-cluster integration tests that we hope can be resolved by using a runner with greater resources available to it.

This first investigation will be to confirm that system resources are indeed the source of our instability.  We can take the simplest route possible of a dedicated VM configured to work with GHAs and target it with our multi-cluster integration tests - all other tests should continue to run on the free-tier runners.

If we can establish success with this we will next look for creative ways to create a pool of self-hosted runners sufficient to fit the parallel execution needs that we have while trying to account for the added cost this would bring.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-933) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-933
┆Priority: Medium

**Comment by jdonenine** [comment]
Some potentially useful info here that @burmanm mentioned earlier:  https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/

Looks like they are working towards making it easier to only run the runners as needed.  We can still for this first effort take the easy path, but might be worth a quick look to see how it works at least.

**Comment by jsanda** [comment]
I changed the title of this issue from `integration tests` to `e2e tests` since there is a distinction to be made within the tests.

**Comment by jsanda** [comment]
I also want to point out that the goal for this ticket is not to have e2e tests running against other k8s distros but rather having existing tests still running against kind on a machine with more resources than what the GHA free runner offers. 

We have #112 to add some initial support for running against different k8s distros.

Assuming that the test instability is due to lack of resources, we to use a machine instance type with sufficient resources but not too much. I say that because we should still be able to run these tests locally as well.

Lastly, we should limit the tests that run on self-hosted runners to those that absolutely need the additional resources above and beyond what the free runner provides.

**Comment by Miles-Garnsey** [comment]
> Assuming that the test instability is due to lack of resources, we need to use a machine instance type with sufficient resources but not too much. I say that because we should still be able to run these tests locally as well. Let me know if this doesn't make sense :)

In the short term would there be benefits to running all tests on both a high-resource and a low-resource runner? This might help us to detect tests which flake when resource constrained. Once we've diagnosed them all we could revert back to a low resource runner for all tests.

**Comment by jsanda** [comment]
I think we already have the low-resource runner covered with the existing free tier runner :) I want to run as many tests as we can there since 1) we get the parallelization for free, 2) we don't have to maintain environments, 3) security is less of a concern.

**Comment by Miles-Garnsey** [comment]
Sure, I just mean to say that it would be good to continue running all tests there in the short term, as well as on whatever new infra we set up. Comparing results across both might be insightful.

**Comment by jsanda** [comment]
Once we have a stable environment for flaky tests (assuming limited resources is the issue) and we have more reliable test runs, I could see the benefit of still running the bigger tests with the free runner. Trying to make it work has definitely helped us identify different issues.

**Comment by jsanda** [comment]
We still need it for k8ssandra-operator but I don't consider it an immediate priority since we have tests stabilized right now. I still consider it a high priority though because we are going to need it eventually. I would like to continue making progress with it, but I don't think it needs to consume all your time.

**Comment by jdonenine** [comment]
Did we leave the runner up and configured?  I don't see any on the org?

![image](https://user-images.githubusercontent.com/7901615/136871069-586cac0c-9d44-4c15-b29d-4b57caeb9edf.png)

**Comment by Miles-Garnsey** [comment]
> Do you know if it is possible to do manual approval for a specific workflow?

I think it is per-repository, so we can't set them for specific workflows unfortunately.
