### ISSUE TITLE
K8SSAND-1357 ⁃ Create Medusa restore mapping in the operator

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#486]
Depending on the results of #485, we should be able to compute restore mappings in the operator directly.
After getting the backup tokenmap from the storage backend, we can generate a mapping file in a config map that will be mounted on the pods for Medusa to read it.
The mapping should look like the following:

```
{
  'in_place': false,
  'host_map':
  {
     'target-node-0': 'source-node-1',
     'target-node-1': 'source-node-3',
     'target-node-2': 'source-node-0',
    ...
  }
}
```

The mapping should respect rack assignments and detecting whether restore is in place or not can be based on overlaps between source node names and projected target pod names.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1357) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1357
┆priority: Medium

**Comment by jsanda** [comment]
ZenHub says that this is blocked by #483. Is that true?

**Comment by Miles-Garnsey** [comment]
> ZenHub says that this is blocked by #483. Is that true?

I think so. I don't think we can compute the mapping unless we have a gRPC endpoint to talk to. My branch is based off the branch in #483.

**Comment by Miles-Garnsey** [comment]
I'm working through the implementation of this. A few assumptions I'm going to make as follows:

* The racks must be balanced. (We can relax this later, but it simplifies an initial implementation).
* The DCs must have the same names in the source and target clusters. Otherwise, it is hard to know which DCs data should be restored into which may pose risks (e.g. GDPR).

**Comment by Miles-Garnsey** [comment]
> Sources can be either IPs or hostnames. No restriction there.

Right, and I guess we actually can't have a restriction because if we did, that will block non-k8ssandra clusters from being restored to k8ssandra clusters right? This is exactly the kind of thing I wanted to validate so thanks for the clarification.

That does change my design a bit, I'm going to have to move away from using the `[inet.af](https://pkg.go.dev/inet.af/netaddr)` package in favour of using strings. I don't like the lack of validation that this will lead to, but on the other hand, we aren't doing anything complex with the addresses and the hostnames would have been strings anyway.
