### ISSUE TITLE
K8SSAND-1634 ⁃ Deleting a single cluster causes other non-affected clusters to abort all PODs & restart

### ISSUE THREAD

**Issue by andrey-dubnik** [k8ssandra/k8ssandra-operator#615]
**What happened?**

Hi, 

We have 2 clusters running associated with a single k8s namespace. We have dropped one cluster which resulted in another cluster to abort all the PODs at the same time and restart triggering a complete loss of service.

**Did you expect to see something different?**

We do not expect the cluster which was not affected by the delete operation to get affected at all.

**How to reproduce it (as minimally and precisely as possible)**:

Create 2 clusters, same namespace (if relevant)
Delete one of the clusters
Remaining cluster will terminate all PODs and they will go into the restart mode

**Environment**

* K8ssandra Operator version: v1.1.1
* Kubernetes version information: 1.22.6
* Kubernetes cluster kind: AKS

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-189) by [Unito](https://www.unito.io)

**Comment by andrey-dubnik** [comment]
It may be related to the fact that we have 2 C* clusters in the same k8s namespace across 2 k8s clusters but we have named the datacenters the same way - primary and secondary.

This resulted in a configuration overlap as cassandra DC name is the same per namespace hence operator was trying to mess with the same DC name across 2 clusters...

**Comment by jsanda** [comment]
@andrey-dubnik can you please provide the K8ssandraCluster manifests so we can test and try to reproduce?

**Comment by jsanda** [comment]
@andrey-dubnik Thanks for sharing your spec. It was easy enough to reproduce the behavior. You are 100% correct that there is a naming collision. We need to adopt a naming convention for the CassandraDatacenters like we do with other resources which is to prefix their names with the K8ssandraCluster name. For your cluster, we would wind up with a CassandraDatacenter named `cluster1-primary`.

The DC name is specified in `/etc/cassandra/cassandra-rackdc.properties.` It is also stored in the `system.local` table.

We want Cassandra to recognize and store the DC name as `primary` (i.e., as specified in manifest), there will be a bit more work involved. It is going to require a small change in cass-operator. I will create the issue for that.

**Comment by burmanm** [comment]
I think the real fix requires some additional steps also. The references (if not Kubernetes controller reference, then something in the Status of K8ssandraCluster) should always correctly point to the objects that have been created (including the cluster it resides in). Not just rely on the naming ideology and hoping they won't clash, but it could even be as far as generating the names with uuid. 

As for "non-cascading delete", that step requires uninstalling cass-operator without removing CRDs before removing the CassandraDatacenter. Otherwise, cass-operator will try to delete the underlying PVCs and remove secret annotations and if it fails, it will hold on to the finalizer and not allow deletion of CassDc.

Also, we might want to check on the "created if not found" policy. If the resource is found which we expect to be created, perhaps we should abort at that point? Otherwise K8ssandraCluster could overwrite an existing CassDc elsewhere as well.

**Comment by jsanda** [comment]
We cannot rely on controller references since the objects we're dealing with can span across multiple Kubernetes clusters. While I am not a huge fan of the datacenters map we currently have in the status (since it just copies the CassandraDatacenters' status verbatim), it does specify each CassandraDatacenter. I'm not sure why we would also need to store the cluster since we can get that from the spec.

I'd say that prefixing the name of the CassandraDatacenter with the name of the K8ssandraCluster or the Cassandra cluster is more than simply hoping that they won't clash. It will prevent collisions in within a namespace-scoped deployment of the operator, even for multi-cluster. It should be sufficient for cluster-scoped deployments of the operator as well.

My suggestion about the non-cascading delete had a slight oversight 😅 What about adding an annotation to the CassandraDatacenter that tells cass-operator it is a non-cascading delete?

I'm not sure about aborting if the resource is found when we expect to create it. We always check first to see if the object exists, and then create if it's not found. We don't do it the other way around, attempting to create the object first.

**Comment by burmanm** [comment]
This is a stale ticket (there's been name overrides for a while), so I'm closing despite the syncing solution waking this up.
