### ISSUE TITLE
Enhance webhook to allow templating of pod name for per-pod secret injection

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#932]
There is a requirement to allow each pod in our statefulsets to mount distinct keystores/truststores. 

To enable a keystore/truststore per Cassandra node, we need to mount a different secret per statefulset pod. Since the statefulset API doesn't allow doing this, we need to leverage the new secret injection webhook created in #605 for this.

We need to add a feature to the webhook so that the annotation can contain a placeholder for the pod name:

```
k8ssandra.io/inject-secret=[{"name": "encryption-stores-${POD_NAME}", "path": "/etc/credentials/cassandra"}]
```

For a pod named `test-dc2-default-sts-1`, the above would mount the `encryption-stores-test-dc2-default-sts-1` secret at `/etc/credentials/cassandra`. 

```[tasklist]
### Definition of Done
- [x] The json format of the annotation should be modified to accept "name" instead of "secretName" to avoid repeating "secret"
- [x] The webhook is capable of substituting ${POD_NAME} with the name of the pod being mutated in the secret name to mount
```

**Comment by Miles-Garnsey** [comment]
@adejanovski I'm looking at this and I'm wondering if it is the wrong way around. Right now in the mutating webhook, my understanding is that the statefulset takes an annotation and the mutating webhook then looks for a secret matching the annotation to mount. This won't work for per-pod secret mounts because the annotation is made at the STS level and every pod will end up with the same annotation (and therefore the same secrets).

I think what you want is something more similar to what I did in some recent monitoring work, where we:

1. Create secrets with an annotation like: `k8ssandra.io/mount-to: '{"pod-name":"test-dc1-default-sts-0", "mount-path": "/data"}'`.
2. Create a mutating webhook so that when a pod is created, the namespace is scanned for secrets targeting that pod name and they are mounted.
3. Create a controller so that when a secret is added with that annotation, pods targeted by the `pod-name` field are updated with the new mounts.

**Comment by adejanovski** [comment]
The annotations aren't placed on the sts but on the pods themselves. Otherwise it would defeat the purpose of this webhook. It's the same for deployments, such as the one we use for reaper: it's not the Deployment object that gets the annotation, it's the pods.

> Would it be better to flip this (similar to some recent monitoring work I've done) so that the secrets are annotated with the pod name?

To the best of my knowledge, that's not how a mutation webhook works. It intercepts the manifest that's about to be applied and then modifies it before it's really applied. We can't intercept secrets and then modify a pod based on what the secret contains, that would lead to all sorts of race conditions. No API call should be made in the mutating webhook either.

**Comment by Miles-Garnsey** [comment]
> The annotations aren't placed on the sts but on the pods themselves. Otherwise it would defeat the purpose of this webhook. It's the same for deployments, such as the one we use for reaper: it's not the Deployment object that gets the annotation, it's the pods.

This appears fine for e.g. superuser secrets and usernames, but it doesn't (for the reasons I've mentioned) appear to give you the ability to have heterogenous secrets per pod in an STS context.

> To the best of my knowledge, that's not how a mutation webhook works. It intercepts the manifest that's about to be applied and then modifies it before it's really applied. We can't intercept secrets and then modify a pod based on what the secret contains, that would lead to all sorts of race conditions. No API call should be made in the mutating webhook either.

It is true that this isn't really a webhook type piece of functionality, it would need to be in the controllers, as I've done for the Mimir ruler. It wouldn't then be webhook related, it is a controller which watches for secrets and reconciles deployments when it sees secrets change.
